### ISSUE TITLE
Hı I use your headergenerator

### ISSUE THREAD

**Issue by Menawan** [smilep/twitter-play#3]
I use your header generetor but when ı want to add paramaters it gives auth error. Can you check that please.
https://stackoverflow.com/questions/62076397/oauth-1-0-could-not-authenticate-you

**Comment by smilep** [comment]
Answer provided on the Stackoverflow question. You need to pass in the request params when calling the service.

Working code is at https://github.com/smilep/twitter-play/blob/master/src/test/java/com/smilep/twitter/PlayTest.java
